### ISSUE TITLE
fix support for include/import

### ISSUE THREAD

**Issue by sloanlance** [sanack/node-jq#104]
With CLI jq, I use the command:
```txt
jq -Mcf filter.jq data.json
```
Where each file contains:
* `filter.jq`
    ```jq
    include "xor";
    map(select(.letters | xor(contains(["a"]); contains(["b"]))))
    ```
* `data.json`
    ```json
    [
        {"letters": ["a", "c"]},
        {"letters": ["a", "b", "c"]},
        {"letters": ["b", "c"]}
    ]
    ```
* `xor.jq` (included by `filter.jq`)
    ```jq
    def xor($a; $b): ($a or $b) and (($a and $b) | not);
    ```
This gives the correct output:
```txt
[{"letters":["a","c"]},{"letters":["b","c"]}]
```

However, when using node-jq in a program, I expect the filter to change and the JSON will already be objects in memory.  So I wrote:

```js
#!/usr/bin/env node

const fs = require('fs');
const jq = require('node-jq');

const jqLocals = 'include "xor";';

const filter =
    jqLocals +
    'map(select(.letters | xor(contains(["a"]); contains(["b"]))))';
const jsonData =
    JSON.parse(
        fs.readFileSync('data.json', 'utf8')
    );
const options = {input: 'json'};

jq.run(filter, jsonData, options).then(console.log);
```

This **_fails_** with the output:

```txt
(node:95910) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: jq: error: syntax error, unexpected include (Unix shell quoting issues?) at <top-level>, line 1:
[{"letters":["a","c"]},{"letters":["a","b","c"]},{"letters":["b","c"]}] | include "xor";map(select(.letters | xor(contains(["a"]); contains(["b"]))))
jq: 1 compile error

(node:95910) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I notice in the error message that node-jq has **_concatenated_** the JSON input with the filter!

I cannot find a solution for this.  What do you recommend?

**Comment by davesnx** [comment]
Hey @sloanlance 

If you simplify your code snippet you realise that you are using the lib a little bit wrong. 
With the default options we look up for a `path` and we read the file and parse for you. 

```js
const fs = require('fs')
const jq = require('node-jq')

const filter = 'include "xor"; map(select(.foo | xor(contains(["a"]); contains(["b"]))))'
jq.run(filter, './data.json').then(console.log).catch(console.error)
// Error: jq: error: module not found: xor
```

Since we currently don't support modules you could just concat the module in the filter, it's kind of ugly but solves your issue:

```js
const fs = require('fs')
const jq = require('node-jq')

const xor = 'def xor($a; $b): ($a or $b) and (($a and $b) | not);'
const filter = xor + 'map(select(.foo | xor(contains(["a"]); contains(["b"]))))'

jq.run(filter, './data.json').then(console.log).catch(console.error)
/* 
[
  {
    "foo": [
      "a",
      "c"
    ]
  },
  {
    "foo": [
      "b",
      "c"
    ]
  }
]
*/
```

That works as you expect. 
We never had the necessity to use modules on **node-jq** and neither the feature request, but I agree would be an easy win.

Hope that it helped. Thanks for open an issue.
PS. I'm keeping the issue open in case that you didn't make that work, ping me if isn't the case.

**Comment by sloanlance** [comment]
Thank you for the response.

I think I wasn't using the lib the _wrong_ way.  The example I showed here only read the JSON file and parsed it before calling node-jq, but my complete application will do a lot more than that.  It will be used to process a large amount of data in memory (several million compacted JSON objects), so I followed the [example in the documentation](/sanack/node-jq/blob/3060ec5/README.md#input-json) to use the `{ input: 'json' }` option.

I'm glad you suggested reading in the `xor.jq` module my filter referenced and adding that to the  filter.  I agree it's not the best solution, but it's good enough for now.  If I have any time available, I'll look into adding features to node-jq to use jq's `--from-file` option.

My sample code is now this:

```js
#!/usr/bin/env node

const fs = require('fs');
const jq = require('node-jq');

// Problem: `include "xor";` at the beginning of filters causes errors.  node-jq serializes
//   input objects to JSON and concatenates the filter to it as "<input> | <filter>".  jq
//   seems to allow "include" directives only at the beginning of filters.
// Workaround: Read the contents of the "xor.jq" file into a constant, then prepend it to filters.
const filterPreamble = fs.readFileSync('xor.jq', 'utf8');
const jqOptions = {input: 'json'};

var filter = 'map(select(.letters | xor(contains(["a"]); contains(["b"]))))';
var data = JSON.parse(fs.readFileSync('data.json', 'utf8'));

jq.run(filterPreamble + filter, data, jqOptions).then(console.log);
```

I think this concept will work well in my initial application release.  The other thing I'm concerned about is node-jq serializing the entire dataset to JSON and passing it to jq on the command line.  I wonder whether it would be better to write the JSON to a temporary file or pass it through `stdin`.

**Comment by iilei** [comment]
>  I wonder whether it would be better to write the JSON to a temporary file or pass it through stdin.

Because that's a documentation bug ([jq #1483](https://github.com/stedolan/jq/issues/1483)) I doubt jq will allow imports in othe places than the beginning.

Therefor im my own project I circumvented the issue by using node-jq with ['file' input](https://github.com/sanack/node-jq/#input).

As it tured out to work well, my question is @davesnx what do you think of the idea of baking this temporary file approach into node-jq? I am willing t contribute a merge request, if you agree it would be a useful change.

**Comment by davesnx** [comment]
Make sense. I would love to design an API that makes sense for this case. Do you want to open a new Issue and we can discuss there? 

I will start with something like: `jq.import().run()`. Where import returns the same instance as now. It wouldn't be a breaking change and just the people that matter about import would use it.

I need to think more but I have a preference for this option rather than another parameter under `jq.run`.

WDYT?

**Comment by iilei** [comment]
By `jq.import().run()` you mean input type `string` would not be able to manage imports?

**Comment by davesnx** [comment]
Yes, `import('xor')` or `import('./absolute/path/to/xor')` both should work.
