### ISSUE TITLE
Clarify the use

### ISSUE THREAD

**Issue by Offirmo** [sanack/node-jq#125]
I wanted to manipulate JSON in a npm script.

Came across this module. However, its behavior is unclear.

- is this module installing jq? Like building it from source somewhere?
- if not, is this module expecting jq to be already installed and in the path?

**Comment by davesnx** [comment]
Hello @Offirmo 

Yes, `node-jq` installs the right binary of `jq` inside `node_modules/.bin` at installation-time.

After that you can use jq in your cli like: `npx jq` or `node_modules/.bin/jq` or even directly `jq` if you are inside the package.json.

I would close this issue, since it's just a question. It's true that we could explain that better on the readme.

**Comment by Offirmo** [comment]
Nice to know!

Is it compatible with Windows, then?

**Comment by davesnx** [comment]
Yes, the details of the binary installation lives here: https://github.com/sanack/node-jq/blob/master/scripts/install-binary.js
