### ISSUE TITLE
Possible issue when dirname has blank spaces

### ISSUE THREAD

**Issue by lfrda** [sanack/node-jq#148]
i'm trying to deploy my application to a server, however i keep getting an error message whenever jq needs to kick in. Upon further investigation I found this in the logs:
```> node-jq@1.3.1 install-binary /opt/jenkins/slave/workspace/MASTER - DEPLOY CAMPAIGN FACTORY SERVER/node_modules/node-jq
> node scripts/install-binary.js

Err: Error: ./configure --disable-maintainer-mode --prefix=/tmp/bcaa7f8b-19ac-47e5-b4ea-2db0ba5bb6e9 --bindir=/opt/jenkins/slave/workspace/MASTER - DEPLOY CAMPAIGN FACTORY SERVER/node_modules/node-jq/bin && make && make install
Command failed: ./configure --disable-maintainer-mode --prefix=/tmp/bcaa7f8b-19ac-47e5-b4ea-2db0ba5bb6e9 --bindir=/opt/jenkins/slave/workspace/MASTER - DEPLOY CAMPAIGN FACTORY SERVER/node_modules/node-jq/bin
configure: error: unrecognized option: `-'
Try `./configure --help' for more information
```
it seems the bin is never generated because the directory's name contains blank spaces

**Comment by davesnx** [comment]
The issue is caused because of your folder structure contains some blank space. We need your folder to install properly jq binary. 

You could do 2 things to fix it:

- Consider removing the blank space from the folder name, because folders with blank spaces it's a pain for all the scripts/cli (https://superuser.com/questions/29111/what-technical-reasons-exist-for-not-using-space-characters-in-file-names)
- Install jq before node-jq using wget directly without a need to compile it from the source or just using your favorite way: https://stedolan.github.io/jq/download/
