### ISSUE TITLE
Fails to install binary

### ISSUE THREAD

**Issue by muxa** [sanack/node-jq#159]
This happens when the directory path being installed into has spaces:

```
> node-jq@1.5.0 install-binary /Users/**/Documents/My Work/***/node_modules/node-jq
> node scripts/install-binary.js

Err: Error: Command failed: /bin/sh -c ./configure --disable-maintainer-mode --with-oniguruma=builtin --prefix=/private/var/folders/pk/t_l2tsvs60v9t57ml3b169c00000gn/T/b6753e4c-840c-4a76-960f-6084f3346015 --bindir=/Users/**/Documents/My Work/***/node_modules/node-jq/bin
configure: WARNING: you should use --build, --host, --target
configure: WARNING: invalid host type: Work/***/node_modules/node-jq/bin
Invalid configuration `Work/***/node_modules/node-jq/bin': machine `Work/***/node_modules/node' not recognized
configure: error: /bin/sh config/config.sub Work/***/node_modules/node-jq/bin failed
```

(On macos)

**Comment by davesnx** [comment]
Hey @muxa, thanks for the issue. 

The issue here is the `/My Work/` folder, right? 
Right now we use `https://github.com/kevva/bin-build` to install the binary from where jq is hosted.

Maybe it's an issue with `bin-build` instead of our install-script. I will take a look and come back. It is actually related with https://github.com/sanack/node-jq/issues/148

**Comment by skitsanos** [comment]
Have the same issue on OSX...

```
Err: Error: Command failed: /bin/sh -c ./configure --disable-maintainer-mode --with-oniguruma=builtin --prefix=/private/var/folders/5g/3zrf856j255591k5l0bzn32r0000gn/T/bfb8f32c-3a9b-4cef-b9e2-82e15919a020 --bindir=/Users/s/server-template/node_modules/node-jq/bin
configure: error: unrecognized option: `-'
Try `./configure --help' for more information
```

**Comment by davesnx** [comment]
The issue is caused because of your folder structure contains some blank space. We need your folder to install properly jq binary. 

You could do 2 things to fix it:

- Consider removing the blank space from the folder name, because folders with blank spaces it's a pain for all the scripts/cli (https://superuser.com/questions/29111/what-technical-reasons-exist-for-not-using-space-characters-in-file-names)
- Install jq before node-jq using wget directly without a need to compile it from the source or just using your favorite way: https://stedolan.github.io/jq/download/
