### ISSUE TITLE
Add installed `jq` to the PATH

### ISSUE THREAD

**Issue by stefanobaghino** [sanack/node-jq#161]
It would be nice to use the [`bin` key](https://docs.npmjs.com/files/package.json#bin) to add a symbolic link of the installed `jq` to the PATH environment variable so that it can be used within the scope of scripts defined in the `package.json` file directly.

Right now it can be used by referring to it as `node_modules/node-jq/bin/jq`, which of course would still be a reasonable compromise if for any reason this cannot be done (e.g.: does it play nice with the possibility of skipping `jq` installation?)

**Comment by davesnx** [comment]
Hey @stefanobaghino 

I remember having those conversations around this [here](https://github.com/sanack/node-jq/issues/142) in this [PR](https://github.com/sanack/node-jq/pull/143)

As I explain my concerns there:

>   It's relying on the current internal on node-jq, If you are using the 1.3.x 
>   version shouldn't be a problem.
>   We don't have any plans to change that, but in the long-run I can't promise that 
>   woudn't change.
> 
>   I'm happy to merge, but as soon as we break that compatibility we should remove 
>   the bin on the package.json.

And... if you skip the installation that would break.
There's no possibility if we point directly to `jq`, but could point into a small bash that checks the env variable to `SKIP_INSTALLATION` and exit with a warning and calls jq with everything else.

Should look something like:
```bash

if ["$NODE_JQ_SKIP_INSTALL_BINARY" == 'true']
then
  echo "jq is not installed in $PATH"
  exit(0)
fi

jq $@
```

Still not 100% convinced about that, because one is an env variable on build time and the check of this bash script is run-time. So, you might end up with a broken experience.

For now, It wouldn't cause much pain, we could live with it. If we see more people asking for this, I would consider splitting the node-jq and the install-jq-binary.

I saw that you open a PR, I would love to have the bash script in that PR. Let me know if you are up to implement it.

**Comment by stefanobaghino** [comment]
Thanks for coming back to me so quickly. Sorry for this kind of "duplication", I searched in the existing issues but apparently I haven't done a good job at it.
> Still not 100% convinced about that, because one is an env variable on build time and the check of this bash script is run-time. So, you might end up with a broken experience.
Yes, this would not be a solution.

At this point I would think about closing both the issue and the PR, but before I do that, could I ask what is the purpose of `NODE_JQ_SKIP_INSTALL_BINARY`? I'm not too much familiar with this library, but I guess the idea is that `jq` is already installed, right? If that's the case, a solution could be for `bin/jq` to be a symlink to `which jq`, right?

But this looks like it's becoming a little bit to hairy, so no problem at all just closing the issue and PR if you feel like it, as I mentioned the matter is just one of shortening the call (I'm basically trying to use `node-jq` as a platform-independent distribution mechanism for `jq` so that it can be used in my `pretest` scripts -- but this would probably be the job of a `install-jq-binary` package).

**Comment by davesnx** [comment]
Hey @stefanobaghino 

It's not documented yet, but `NODE_JQ_SKIP_INSTALL_BINARY` assumes that you have jq already installed and you know where jq lives ($PATH or directly the absolute).

For the sake of solving your shortening, let's merge the PR (since other people asked for this as well). We can figure it out later making a breaking change.

**Comment by stefanobaghino** [comment]
Cool, thanks.

**Comment by davesnx** [comment]
I remove it from the packagejson, you could use `npx jq` if you want to point into jq binary.
Because npm tried to change the permisions before installing and we had a few people breaking their builds with that.
