### ISSUE TITLE
Usage with Node Streams - Documentation

### ISSUE THREAD

**Issue by doArcanjo** [sanack/node-jq#205]

**Comment by davesnx** [comment]
Hey @doArcanjo,

Could you elaborate more? I assume you need documentation on using node native streams with node-jq?

Do you have any use-case for that?

**Comment by doArcanjo** [comment]
I do, pipe a streamed result dataset, being fetched from an API, into jq, and streaming out(again) the results.
Thank you

**Comment by btakita** [comment]
+1 I've been using `spawn` with `jq`. Here's an example:

```js
const { spawn } = require('child_process')
const limit = 10
const jq = spawn(
	'jq',
	[
		'-r',
		`
[
.logStreams
|= sort_by(.creationTime)
| .[]
| reverse
| limit(${limit};.[])
]
| reverse
		`.trim()
	]
)
process.stdin.pipe(jq)
jq.stdout.pipe(process.stdout)
jq.stderr.pipe(process.stderr)
jq.on('close', process.exit)
```

**Comment by davesnx** [comment]
Hey @doArcanjo,

I still don't get why would you use node-jq which is a wrapper around jq to run operations to transform the response of a request, since you would open a spawn to bash to get the transformations and back, seems not the ideal solution; but I might miss some context here that might discard what I just wrote.

But going on the same direction, running jq inside a node script to allow piping (in the context of bash) seems a sub-optimal idea when you can use jq straight?

@doArcanjo, I don't have any example of using node Streams using node-jq, so feel free to share it here and I will try to come up with a doc in the readme.

Thanks for commenting and opening the issue.
