### ISSUE TITLE
impossible to use node-jq with large json

### ISSUE THREAD

**Issue by Horsty80** [sanack/node-jq#389]
## Description

I'm trying to reproduce a Jq command with node-jq on a large json.
I use Jq to help me to parse it by reduce considerably is size by omit some attribut on it.

The json is like this : 
```json
{
    "meta":{
        "date":"2021-04-03",
        "version":"5.1.0+20210403"
        },
        "data":{
    ... Big structured json 
         }
}
```
When i launch this Jq command in my terminal there are no problem Jq works fine and i get the result that i expect

```jq
jq '.data | to_entries | map_values(.value + { slug: .key }) | del(.. | objects | .paper.cardkingdom) | del( .. | objects | .paper.tcgplayer.buylist)' AllPrices.json > prices.json
```
When i implement it on my node project, i've got the error because the json is too big
```error
Error: jq: error (at ./src/ressources/allPrices.json:0): Cannot index array with string "data"
```
That is my js code
```js
  const filter = '.data | to_entries | map_values(.value + { slug: .key }) | del(.. | objects | .paper.cardkingdom) | del( .. | objects | .paper.tcgplayer.buylist)';
  const options = {
    output: 'pretty', slurp: true
  }
  const pathToJson = `./src/${dir}/AllPrices.json`;
  jq.run(filter, pathToJson, options).then((output) => {
    fs.writeFileSync(`./src/${dir}/prices.json`, JSON.stringify(output, null, 2), "utf8");
  }).catch((err) => {
    console.error(err)
  });
```

### Error Message & Stack Trace

```
> cron-jobs-node@1.0.0 start /Users/cyril/Workspace/cron-jobs-node
> node --stack-size=4096 --max_old_space_size=8192 .

Error: jq: error (at ./src/ressources/allPrices.json:0): Cannot index array with string "data"

    at ChildProcess.<anonymous> (/Users/cyril/Workspace/cron-jobs-node/node_modules/node-jq/lib/exec.js:45:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1051:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
```

## Relevant Links

You can find the json on this website [MtgJson](https://mtgjson.com/downloads/all-files/#allprices)
that is the direct download link of the large json [AllPrices.json](https://mtgjson.com/api/v5/AllPrices.json)

## Environment

Node.js v14.2.0
darwin 20.3.0

**Comment by davesnx** [comment]
Hey @Horsty80,

Sorry to have troubles with node-jq. There shouldn't be any problem with node reading a json file, running a child_process and later print it to the console (or save it to the file system).

and after a few tests I realized that there's no such problem with node-jq. If you run jq from the cli with `-slurp` that expects that the json is paginable (or in a more functional way, the operation needs to be associative).

In your case, since the filter happens inside ".data" it's not the case.

```
jq -s '.data | to_entries | map_values(.value + { slug: .key }) | del(.. | objects | .paper.cardkingdom) | del( .. | objects | .paper.tcgplayer.buylist)' data.json
```

Gives similar error: `jq: error (at data.json:0): Cannot index array with string "data"`.

If you remove slurp from the node script, you should have it working fine.

**Comment by Horsty80** [comment]
Thanks @davesnx !! 
I misunderstood `-slurp` option, i didn't need it so i remove it and it's work perfectly :)
awesome !!
