### ISSUE TITLE
jq binary

### ISSUE THREAD

**Issue by SRachamim** [sanack/node-jq#390]
The documentation says:

> After that to run jq directly. Like: ./node_modules/node-jq/bin/jq . package.json.

This is a bad practice. We should not encourage people to access a binary in a `node_modules`. This is a workaround-hack.

I suggest to either install `jq` as a standard binary (see `tsc`, `shellcheck` and *many* more example) or remove it from the documentation.

**Comment by davesnx** [comment]
Hey @SRachamim 

**node-jq** installs `jq` as a "standard" binary, whatever that "standard" means to you. I'm surprised that you mention that having a binary under node_modules is a "workaround-hack", while most packages in the node ecosystem include their binaries under `node_modules/bin`.

Since it's installing `jq` from the wire on a post-install script, I couldn't make it work with the "bin" field on package.json. Making many users complain about that, (you can search in issues). I even create an issue in SO 3 years ago. https://stackoverflow.com/questions/57007962/where-a-binary-inside-a-javascript-module-should-live

Happy to work on a solution that works everywhere, for now I'm closing this since isn't an issue.

**Comment by SRachamim** [comment]
Sorry, I don't pretend to kno what's really a standard, but I use to expect `tsc`, `eslint` and other binaries available on my `npm` scripts, while `jq` behaves differently.
