### ISSUE TITLE
node-jq throw E2BIG error when input json is too big

### ISSUE THREAD

**Issue by qifuren1985** [sanack/node-jq#51]
If input json is big array, it will throw E2BIG error.
for example, type this code in chrome console, it will generate a big array, and copy to clipboard.
```js

function gen_data() {
  var ret = [];
  for (var i=0; i < 10000; i++) {
    ret.push({"name": i , "kk": i * 2})
  }
  return ret;
}

copy(JSON.stringify(gen_data()));

```

when pass a array with 10000 elements to node-jq, it will throw E2BIG, due to a limitation of the size of the command line argument.

jq support read json string from stdin, so when call child_process to create process, we need pass json string to new process from stdin to fix this bug.

**Comment by davesnx** [comment]
Hello @qifuren1985 

I did a test and it's true there's a 'bug' arround E2BIG.

For reproduce I did this snippet:

```js
const { run } = require('node-jq')
const fill = require('lodash.fill')

const filter = '. | map(select(.name > 1))'
const array2BIG = JSON.stringify(fill(Array(10000), { name: 2, lola: 'name' }))
const options = { input: 'string' }

run(filter, array2BIG, options)
  .then((output) => {
    console.log(output.length)
  })
  .catch((err) => {
    console.error(err)
  })
```

and the error that I get is:

```bash
{ Error: spawn E2BIG
    at exports._errnoException (util.js:1036:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at exports.spawn (child_process.js:380:9)
    at Object.exports.execFile (child_process.js:143:15)
    at Object.exports.exec (child_process.js:103:18)
    at /Users/davidsancho/dev/nodejqE2BIG/node_modules/node-jq/lib/exec.js:21:29
    at exec (/Users/davidsancho/dev/nodejqE2BIG/node_modules/node-jq/lib/exec.js:20:10)
    at /Users/davidsancho/dev/nodejqE2BIG/node_modules/node-jq/lib/jq.js:39:24
    at run (/Users/davidsancho/dev/nodejqE2BIG/node_modules/node-jq/lib/jq.js:34:10)
    at Object.<anonymous> (/Users/davidsancho/dev/nodejqE2BIG/index.js:8:1) code: 'E2BIG', errno: 'E2BIG', syscall: 'spawn' }
```

Let me explain what's happening here. The `E2BIG` means that the argument list is too long, as you point it out.

Depend on which OS are you runnig node-jq, could you try to run `getconf ARG_MAX` in your terminal, will output the Maximum bytes per argument that your shell can run. It's pretty well explained [here](http://unix.stackexchange.com/questions/120642/what-defines-the-maximum-size-for-a-command-single-argument).

It's basically an error of child-process on node... [:sad:](http://stackoverflow.com/questions/36251711/node-child-process-throwing-e2big)

**Comment by davesnx** [comment]
Doing a little bit more of research arround that. I can add another workarround: Just increasing the `ARG_MAX` of you OS. [here](http://www.in-ulm.de/~mascheck/various/argmax/)

**Comment by davesnx** [comment]
Also we are thinking [to support Node Streams](https://github.com/sanack/node-jq/issues/36) matching with `jq` streams.

**Comment by qifuren1985** [comment]
I means:
`
const spawn = require('child_process').spawn;
const child = spawn('jq', [". | map(select(.name > 1))"]);
const fill = require('lodash.fill');

child.stdout.on('data', (data) => {
  console.log(`${data}`);
});

child.stdin.setEncoding('utf-8');
const array2BIG = JSON.stringify(fill(Array(10000), { name: 2, lola: 'name' }))
child.stdin.write(array2BIG);
child.stdin.end()
`

**Comment by davesnx** [comment]
Oh @qifuren1985, I see what you mean.

I like the idea we could extend the API of node-jq, to have the possibility to add stuff on the stdin.

I will ping you again If we finish with this. 
Thanks for the issue man! Let me know if you found something that node-jq can be better.

**Comment by lmeyerov** [comment]
@davesnx  FWIW we just hit this as well on a 300KB file, with OS X being at 262KB

**Comment by lostnet** [comment]
This problem seems to look a little [different on windows](https://stackoverflow.com/questions/57166113/how-to-fix-error-spawn-enametoolong-probably-cause-by-jq-in-javascript) as it seems windows reports ENAMETOOLONG for reasons other than PATH_MAX.

Here is a test case that an input file more than 2*ARG_MAX ("1," * ARG_MAX) can be processed as `[input] | jq [filter]` as @qifuren1985 proposed, but not in the `jq -n '[input]|[filter]'` fashion node-jq is using.

```
$ ARG_MAX=`getconf ARG_MAX` jq -c -n '[range(env.ARG_MAX|tonumber)|1]' > out.json
$ cat out.json | jq . > /dev/null
$ echo $?
0
$ echo '| .' >> out.json
$ jq -n `cat out.json`
-bash: ...jq: Argument list too long
$ echo $?
126
```

**Comment by davesnx** [comment]
Using json as an input fails at: 300KB file. event with OS X being at 262KB?

About @lostnet, it related with this right?
support.microsoft.com/sv-se/help/830473/command-prompt-cmd--exe-command-line-string-limitation.

I can't really do anything from the node-jq side, atleast recommend to lightwight your json before sending it to node-jq. Maybe paginate it, maybe chunk it, depends on your data.

**Comment by lostnet** [comment]
@davesnx right, it is something <8k on windows, [<128k on linux and <262k on osx](https://www.in-ulm.de/~mascheck/various/argmax/). This is because node-jq does [this](https://github.com/sanack/node-jq/blob/master/src/options.js#L27) instead of retaining the data as a separate argument to send separately [here](https://github.com/sanack/node-jq/blob/master/src/exec.js#L11) using process.stdin.write(). My test case demonstrates that it is up to a caller (node-jq) to decide if it wants to hit the OS limits on args or use stdin. A caller that is a user doing one test case might like -n, a FFI that doesn't know much about its input should not choose to use arguments the way node-jq does.

Given that this is also exposing json in os arguments to whoever else and the exact amount that is too much will be entirely unknown as it relates to other content of the call and environment, I really don't think node-jq should be providing these input options at all if it is going to send data via args instead of stdin.

**Comment by mackermans** [comment]
@lostnet I opened #194 which should fix this issue. Could you check it out and let me know if it works for you?

**Comment by lostnet** [comment]
Thank you @mackermans the test case and use of stdin are consistent with fixing the problem I was seeing. I added a comment in 194 since I'm not sure if it could add a regression for people that actually try to send an empty text input. I think that always failed given the argument to the old version, but it might leave a hanging jq now..

**Comment by lostnet** [comment]
Thanks @mackermans I tested that the new version passes on my linux host that was failing bellow the 128k mark with the old node-jq. I opened issue #195 for the potential of an edge case hang since this is already integrated.

**Comment by mackermans** [comment]
Thanks, @lostnet. I confirmed the just released stdin version does indeed hang on several cases. I'll open up a PR to throw errors based on those inputs, to be compatible with the previous versions again.
