### ISSUE TITLE
".[]" filter syntax does not work correctly

### ISSUE THREAD

**Issue by wellsjo** [sanack/node-jq#52]
In the terminal, I get:
```bash
echo "[1, 2, 3]" | jq .[]
1
2
3
```

Using `node-jq`: 
```javascript
jq.run('.[]', [1, 2, 3], { input: 'json', output: 'json' })
  .then(r => console.log(r))
  .catch(e => console.log(e))
```
I get the following error message:
```bash
SyntaxError: Unexpected number in JSON at position 2
    at Object.parse (native)
    at /Users/wells/src/jsp/node_modules/node-jq/lib/jq.js:41:29
```
I tested this using both `json` and `file` input types.

**Comment by davesnx** [comment]
Hello @wellsjo,

That's basically because an array isn't a valid JSON Object. When JS tries to parse it, gives that generic error 😢.

We can talk about support JSON5 parsing for solve your issues or do a silly-condition for this simple case.

```js
if (isArray([1, 2, 3])) {
  transformToValidJSON([1, 2, 3])
  // Will transform into a object with a key '.' containing the array like that: {'.': [1, 2, 3]}
}
```

I'm balanced more for support JSON5. 
Any thoughts @mackermans and @wellsjo?

**Comment by wellsjo** [comment]
Array literals are part of the JSON spec though (see [json.org](http://www.json.org/)). And the following works:
```javascript
JSON.parse('[1, 2, 3]')
```
So why would any JS parsing cause errors?

**Comment by davesnx** [comment]
Sorry @wellsjo, I was wrong, I update the answer.

**Comment by wellsjo** [comment]
@davesnx Ah, I see what's going on. I updated my answer above!
