### ISSUE TITLE
Add native C/C++ bindings to jq

### ISSUE THREAD

**Issue by matthewadams** [sanack/node-jq#86]
Refactor the strategy of shelling out to call `jq` to making `node-jq` an actual native Node.js module, as per https://nodejs.org/dist/latest-v6.x/docs/api/addons.html.

The current strategy incurs the performance overhead of launching an external command, whereas a native invocation would not.

**Comment by matthewadams** [comment]
Also see https://github.com/stedolan/jq/issues/1267

**Comment by davesnx** [comment]
Hi @matthewadams 

We thought about that a few times, we never get really deep on that basically because I never did any C/C++ port to Node.js.

As far as I know you can run `jq` as a programatically API and that lives in [`jv.h`](https://github.com/stedolan/jq/blob/master/src/jv.h) and potentially you could do an addon with Node with that.

I will try to implement it, I will come back when I have something real.

Thanks for pointing out @matthewadams 
Can we know why you would need that? It's only curiosity ;)

**Comment by matthewadams** [comment]
I'm expecting the current implementation not to pass muster during a code review in my current organization when they look for scaling issues.

**Comment by LaurentGoderre** [comment]
I would be really interested in this as well. I found the following article and hope I can take a stab at it soon.

https://pravinchavan.wordpress.com/2013/11/08/c-binding-with-node-js/

**Comment by ericlewis** [comment]
I created a C addon, but performance wise, I’m not sure it’s any better. Average run time using this lib was 11ms, calling the library natively was 30ms.

**Comment by davesnx** [comment]
I don't see any evidence of improvement on performance with native bindings.

> The current strategy incurs the performance overhead of launching an external command, whereas a native invocation would not.

If what @ericlewis said was true, I will close this issue and maybe consider it to add it on the README.

Thanks everyone!
